config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :names
  # do
    # collection do
    #   get "search"
    # end
  # end

  resources :educators
  # do
  #   collection do
  #     get "search"
  #   end
  # end

  get "about", to: "about#index", as: "about"

  root to: "names#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :name
  has_one :name
  has_many :name

  # validates
  validates :city, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/educator.rb
class Educator < ApplicationRecord
belongs_to :name
has_many :name
has_many :city

# Validation check
validates :university, :coursename, presence: true

  def self.search_by(search_term)
    where("LOWER(university) LIKE :search_word", search_word: "%#{search_word.downcase}%")
  end
end

app/models/name.rb
class Name < ApplicationRecord
  belongs_to :educator
  belongs_to :address
  has_one :university
  has_one :address
  has_many :coursename

  # validations
  valildates name:, presence: true, uniqueness: true

  def self.search_by(search_term)
    where("LOWER(name) LIKE :search_term", search_term: "%#{search_term.downcase}%")
    # OR LOWER(course) LIKE :search_term
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to address_url(@address), notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:city)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/educators_controller.rb
class EducatorsController < ApplicationController
  before_action :set_educator, only: %i[ show edit update destroy ]

  # GET /educators or /educators.json
  def index
    if params[:searchresult]
      @search_word = params[:searchresult]
      @educators = @educators.search_by(@search_term)
    end
    @educators = Educator.paginate(page: params[:page], per_page: 30)
  end

  # GET /educators/1 or /educators/1.json
  def show
  end

  # GET /educators/new
  def new
    @educator = Educator.new
  end

  # GET /educators/1/edit
  def edit
  end

  # POST /educators or /educators.json
  def create
    @educator = Educator.new(educator_params)

    respond_to do |format|
      if @educator.save
        format.html { redirect_to educator_url(@educator), notice: "Educator was successfully created." }
        format.json { render :show, status: :created, location: @educator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @educator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educators/1 or /educators/1.json
  def update
    respond_to do |format|
      if @educator.update(educator_params)
        format.html { redirect_to educator_url(@educator), notice: "Educator was successfully updated." }
        format.json { render :show, status: :ok, location: @educator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @educator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educators/1 or /educators/1.json
  def destroy
    @educator.destroy

    respond_to do |format|
      format.html { redirect_to educators_url, notice: "Educator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_educator
      @educator = Educator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def educator_params
      params.require(:educator).permit(:university, :coursename)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
  #   @names = Name.all.paginate(page: params[:page], per_page: 30)
  #   @educators = Name.all.paginate(page: params[:page], per_page: 30)
  end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_action :set_name, only: %i[ show edit update destroy ]

  # GET /names or /names.json
  def index
    # @names = Name.all
    @names = Name.all.paginate(page: params[:page], per_page: 30)
    if params[:search]
      @search_term = params[:search]
      @names = @names.search_by(@search_term)
    end
  end

  # GET /names/1 or /names/1.json
  def show
    @name = Name.find(params[:id])
  end

  # GET /names/new
  def new
    @name = Name.new
  end

  # GET /names/1/edit
  def edit
  end

  # POST /names or /names.json
  def create
    @name = Name.new(name_params)

    respond_to do |format|
      if @name.save
        format.html { redirect_to name_url(@name), notice: "Name was successfully created." }
        format.json { render :show, status: :created, location: @name }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /names/1 or /names/1.json
  def update
    respond_to do |format|
      if @name.update(name_params)
        format.html { redirect_to name_url(@name), notice: "Name was successfully updated." }
        format.json { render :show, status: :ok, location: @name }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /names/1 or /names/1.json
  def destroy
    @name.destroy

    respond_to do |format|
      format.html { redirect_to names_url, notice: "Name was successfully destroyed." }
      format.json { head :no_content }
    end

    def search
      wildcard_search = "%#{params[:keywords]}%"
      @names = Name.where("name LIKE ?", wildcard_search)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_name
      @name = Name.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def name_params
      params.require(:name).permit(:name)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/educators_helper.rb
module EducatorsHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/about/index.html.erb
<h1>About</h1>

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>">
  <p>
    <strong>City:</strong>
    <%= address.city %>
  </p>

</div>

app/views/addresses/_form.html.erb
<%= form_with(model: address) do |form| %>
  <% if address.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Show this address", @address %> |
  <%= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Addresses</h1>

<div id="addresses">
  <% @addresses.each do |address| %>
    <%= render address %>
    <p>
      <%= link_to "Show this address", address %>
    </p>
  <% end %>
</div>

<%= link_to "New address", new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to "Back to addresses", addresses_path %>
</div>

app/views/addresses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @address %>

<div>
  <%= link_to "Edit this address", edit_address_path(@address) %> |
  <%= link_to "Back to addresses", addresses_path %>

  <%= button_to "Destroy this address", @address, method: :delete %>
</div>

app/views/educators/_educator.html.erb
<div id="<%= dom_id educator %>">
  <p>
    <strong>University:</strong>
    <%= educator.university %>
  </p>

  <p>
    <strong>Coursename:</strong>
    <%= educator.coursename %>
  </p>

</div>

app/views/educators/_form.html.erb
<%= form_with(model: educator) do |form| %>
  <% if educator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(educator.errors.count, "error") %> prohibited this educator from being saved:</h2>

      <ul>
        <% educator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :university, style: "display: block" %>
    <%= form.text_field :university %>
  </div>

  <div>
    <%= form.label :coursename, style: "display: block" %>
    <%= form.text_field :coursename %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/educators/edit.html.erb
<h1>Editing educator</h1>

<%= render "form", educator: @educator %>

<br>

<div>
  <%= link_to "Show this educator", @educator %> |
  <%= link_to "Back to educators", educators_path %>
</div>

app/views/educators/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>University and Courses</h1>
<%= link_to "New educator", new_educator_path %>

<%= form_for "", url: educators_path, role: "search", method: :get do %>
  <%= text_field_tag :searchresult, @search_word,placeholder: "Search..." %>
<% end %>

<div id="educators">
  <% @educators.each do |educator| %>
    <%= render educator %>
    <p>
      <%= link_to "Show this educator", educator %>
    </p>
  <% end %>
</div>


<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">University</th>
      <th scope="col">Course Name</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry</td>
      <td>the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>




<%= will_paginate @educators, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/educators/new.html.erb
<h1>New educator</h1>

<%= render "form", educator: @educator %>

<br>

<div>
  <%= link_to "Back to educators", educators_path %>
</div>

app/views/educators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @educator %>

<div>
  <%= link_to "Edit this educator", edit_educator_path(@educator) %> |
  <%= link_to "Back to educators", educators_path %>

  <%= button_to "Destroy this educator", @educator, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>Welcome to da Home Page! YURRRRR</h1>
</div>

<div class="container">
  <% @names.each do |name| %>
    <li><%= link_to name.name %></li>
  <%end %>
</div>

<%= will_paginate @names, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/navbar"%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/names/_form.html.erb
<%= form_with(model: name) do |form| %>
  <% if name.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(name.errors.count, "error") %> prohibited this name from being saved:</h2>

      <ul>
        <% name.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/names/_name.html.erb
<div id="<%= dom_id name %>">
  <p>
    <strong>Name:</strong>
    <%= name.name %>
  </p>

</div>

app/views/names/edit.html.erb
<h1>Editing name</h1>

<%= render "form", name: @name %>

<br>

<div>
  <%= link_to "Show this name", @name %> |
  <%= link_to "Back to names", names_path %>
</div>

app/views/names/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<%= form_for "", url: names_path, role: "search", method: :get do %>
  <%= text_field_tag :search, @search_term,placeholder: "Search..." %>
<% end %>

<%= link_to "New Student", new_name_path %>

<div id="names">
  <% @names.each do |name| %>
    <%= render name %>
    <p>
      <%= link_to "Show Student Information", name %>
    </p>
  <% end %>
</div>

<%= will_paginate @names, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/names/new.html.erb
<h1>New name</h1>

<%= render "form", name: @name %>

<br>

<div>
  <%= link_to "Back to names", names_path %>
</div>

app/views/names/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @name %>

<div>
  <%= link_to "Edit this name", edit_name_path(@name) %> |
  <%= link_to "Back to names", names_path %>

  <%= button_to "Destroy this name", @name, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "SKOOL", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Names", names_path, class: "nav-link"%></li>
            <li><%= link_to "Educators", educators_path, class: "nav-link"%></li>
            <li><%= link_to "Addresses", addresses_path, class: "nav-link"%></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
  </div>
</nav>